[package]
name = "deps_cop"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.10"
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.152"
serde-xml-rs = "0.5.1"