name: Publish .deb file to packagecloud

on:
  release:
    types: [created]

jobs:
  publish-to-packagecloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download .deb file from release
        run: |
          wget https://github.com/tecnocrata/deps-cop/releases/download/${{ github.event.release.tag_name }}/depscop-deb.deb

      - name: push package to packagecloud.io
        uses: computology/packagecloud-github-action@v0.6
        with:
    ##### MODIFY: Change to packagecloud username, reponame, distro type
    #####         To understand the available distro type, see https://www.rubydoc.info/gems/package_cloud/#pushing-a-package
            PACKAGE-NAME: depscop-deb.deb
            PACKAGECLOUD-USERNAME: tecnocrata
            PACKAGECLOUD-REPONAME: deps-cop
            PACKAGECLOUD-DISTRO: any/any
            PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}