name: Create WinGet PR

on:
  release:
    types: [created]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Update manifest
      run: |
        VERSION=${{ github.event.release.tag_name }}
        ZIP_URL="https://github.com/tecnocrata/deps-cop/releases/download/${VERSION}/depscop-windows-v${VERSION}.zip"
        sed -i "s|InstallerUrl: .*|InstallerUrl: ${ZIP_URL}|" manifests/winget/depscop.yaml
        sed -i "s/PackageVersion: .*/PackageVersion: ${VERSION}/" manifests/winget/depscop.yaml
        sed -i "s/ManifestVersion: .*/ManifestVersion: ${VERSION}/" manifests/winget/depscop.yaml
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT_RELEASE }}
        commit-message: Update manifest for ${{ github.event.release.tag_name }}
        committer: GitHub Actions <actions@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: update-winget-manifest
        base: microsoft/winget-pkgs
        path: manifests/tecnocrata/depscop
        delete-branch: true